# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JF/kRet/6tSo9A9Ij2XHbMCctHT0CqSoLV5e6ZthiFvDfSXigiZh4G3JQo1NccHw5RjJl7KYkr5toqPETl20vQwPUaQ+kEPTc2n0mCmFbaCMcT9gKv//Z8KQD8lYqDLzUFQCu41qkbcl5XUJ3nZeOQZ8OLcjkORY63WwuKLNtEckelRkXwdbVAumRBnqGzNtIXLVC/SHrRNt6YY6Pk+/N2UqWgApdo0izLyPEVxJgsWgscuK8KFFvyxaTQIbdGqDTVAjQfDc6OLlsV09cIgFV7j529BhrIp6sQx2WqZMEo3SMPSsCRIunbSFxAmbxnpuMtHk6MNki2WVmpR14l5zUDcwESF16EeiRHF3dvcEtpRC2JhVv7tcmstRi8v0S++EXXxBDphYxtgzQXQA2r0ijlMh3i8E6llmCNpkob/Qlyczk25FlrD2a4CgNjCW2D3Si1WJHFnbF8bW/IJNnuNoGJhNIHvtB2pEnvqADGaWEcPlUOMR6ugblmtFBxycZ6sEt5tRxVum8pLtYihYAK8AjXxkek6eM5aJ1Uo/VpFQuFiasmW36r3ulbTXZXnnbOvRf4G32w4c36ksYM2yC0UQ/DSs9MHuRgrIeo2gIeOX+H9Vc3Aw9LjH5Tek1w1H7dyBa5zUE9DiAKU+7q8f2s+lchibz+K2QMX6Eop3eUAeqgQ="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_python2.7target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le
      os: linux-ppc64le

    - env: CONFIG=linux_ppc64le_python3.6target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le
      os: linux-ppc64le

    - env: CONFIG=linux_ppc64le_python3.7target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le
      os: linux-ppc64le

script:


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then pip install shyaml --user && ./.travis/run_docker_build.sh; fi